// Generated by IcedCoffeeScript 1.7.1-b
(function() {
  var exp, k, v, _ref;

  exp = {
    defaults: {
      filename: 'SIGNED.md'
    },
    item_types: {
      FILE: 0,
      DIR: 1,
      SYMLINK: 2,
      WIN_SYMLINK: 3
    },
    presets: {
      GIT: 'ignore anything as described by .gitignore files',
      KB: 'ignore anything as described by .kbignore files',
      DROPBOX: 'ignore .dropbox-cache and other Dropbox-related files',
      NONE: 'don\'t ignore anything'
    },
    ignore_res: {
      NONE: 0,
      IGNORE: 1,
      DONT_IGNORE: 2
    },
    item_type_names: {}
  };

  _ref = exp.item_types;
  for (k in _ref) {
    v = _ref[k];
    exp.item_type_names[v] = k;
  }

  module.exports = exp;

}).call(this);
