// Generated by IcedCoffeeScript 1.7.1-b
(function() {
  var exp, k, v, _ref;

  exp = {
    defaults: {
      filename: 'SIGNED.md'
    },
    item_types: {
      FILE: 0,
      DIR: 1,
      SYMLINK: 2
    },
    item_type_names: {}
  };

  _ref = exp.item_types;
  for (k in _ref) {
    v = _ref[k];
    exp.item_type_names[v] = k;
  }

  module.exports = exp;

}).call(this);
