// Generated by IcedCoffeeScript 1.7.1-b
(function() {
  module.exports = {
    defaults: {
      filename: 'SIGNED.md'
    },
    item_types: {
      FILE: 0,
      DIR: 1,
      SYMLINK: 2
    }
  };

}).call(this);
