// Generated by IcedCoffeeScript 1.7.1-b
(function() {
  var FileInfo, InfoCollection, LockTable, XPlatformHash, crypto, fs, ic, iced, path, utils, __iced_k, __iced_k_noop;

  iced = require('iced-coffee-script/lib/coffee-script/iced').runtime;
  __iced_k = __iced_k_noop = function() {};

  path = require('path');

  fs = require('fs');

  crypto = require('crypto');

  LockTable = require('./lock').Table;

  utils = require('./utils');

  XPlatformHash = require('./x_platform_hash');

  FileInfo = (function() {
    function FileInfo(full_path) {
      this._BINARY_BYTE_STUDY = 8000;
      this.full_path = full_path;
      this.err = null;
      this.lstat = null;
      this.stat = null;
      this._hash = {};
      this._is_binary = null;
      this._dir_contents = null;
      this._locks = new LockTable();
      this._init_done = false;
      this._link = null;
    }

    FileInfo.prototype.init = function(cb) {
      var err1, err2, ___iced_passed_deferral, __iced_deferrals, __iced_k;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      (function(_this) {
        return (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "/Users/chris/git/keybase/dir-summarize/src/file_info_cache.iced",
            funcname: "FileInfo.init"
          });
          fs.stat(_this.full_path, __iced_deferrals.defer({
            assign_fn: (function(__slot_1) {
              return function() {
                err1 = arguments[0];
                return __slot_1.stat = arguments[1];
              };
            })(_this),
            lineno: 41
          }));
          fs.lstat(_this.full_path, __iced_deferrals.defer({
            assign_fn: (function(__slot_1) {
              return function() {
                err2 = arguments[0];
                return __slot_1.lstat = arguments[1];
              };
            })(_this),
            lineno: 42
          }));
          __iced_deferrals._fulfill();
        });
      })(this)((function(_this) {
        return function() {
          _this.err = err1 || err2;
          _this._init_done = true;
          return cb();
        };
      })(this));
    };

    FileInfo.prototype.check_init = function() {
      if (!this._init_done) {
        throw new Error("Init not done on " + this.full_path);
      }
    };

    FileInfo.prototype.hash = function(alg, encoding, cb) {
      var fd, h, k, lock, ___iced_passed_deferral, __iced_deferrals, __iced_k;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      this.check_init();
      k = "" + alg + "|" + encoding;
      (function(_this) {
        return (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "/Users/chris/git/keybase/dir-summarize/src/file_info_cache.iced",
            funcname: "FileInfo.hash"
          });
          _this._locks.acquire(k, __iced_deferrals.defer({
            assign_fn: (function() {
              return function() {
                return lock = arguments[0];
              };
            })(),
            lineno: 57
          }), true);
          __iced_deferrals._fulfill();
        });
      })(this)((function(_this) {
        return function() {
          (function(__iced_k) {
            if ((!_this.err) && (_this._hash[k] == null)) {
              h = new XPlatformHash({
                alg: alg,
                encoding: encoding
              });
              fd = fs.createReadStream(_this.full_path);
              (function(__iced_k) {
                __iced_deferrals = new iced.Deferrals(__iced_k, {
                  parent: ___iced_passed_deferral,
                  filename: "/Users/chris/git/keybase/dir-summarize/src/file_info_cache.iced",
                  funcname: "FileInfo.hash"
                });
                h.hash(fd, __iced_deferrals.defer({
                  assign_fn: (function(__slot_1, __slot_2, __slot_3) {
                    return function() {
                      __slot_1.err = arguments[0];
                      return __slot_2[__slot_3] = arguments[1];
                    };
                  })(_this, _this._hash, k),
                  lineno: 61
                }));
                __iced_deferrals._fulfill();
              })(__iced_k);
            } else {
              return __iced_k();
            }
          })(function() {
            lock.release();
            return cb(_this.err, _this._hash[k]);
          });
        };
      })(this));
    };

    FileInfo.prototype.dir_contents = function(cb) {
      var f, fnames, lock, ___iced_passed_deferral, __iced_deferrals, __iced_k;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      this.check_init();
      (function(_this) {
        return (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "/Users/chris/git/keybase/dir-summarize/src/file_info_cache.iced",
            funcname: "FileInfo.dir_contents"
          });
          _this._locks.acquire('dir_contents', __iced_deferrals.defer({
            assign_fn: (function() {
              return function() {
                return lock = arguments[0];
              };
            })(),
            lineno: 69
          }), true);
          __iced_deferrals._fulfill();
        });
      })(this)((function(_this) {
        return function() {
          (function(__iced_k) {
            if ((!_this.err) && (_this._dir_contents == null)) {
              (function(__iced_k) {
                __iced_deferrals = new iced.Deferrals(__iced_k, {
                  parent: ___iced_passed_deferral,
                  filename: "/Users/chris/git/keybase/dir-summarize/src/file_info_cache.iced",
                  funcname: "FileInfo.dir_contents"
                });
                fs.readdir(_this.full_path, __iced_deferrals.defer({
                  assign_fn: (function(__slot_1) {
                    return function() {
                      __slot_1.err = arguments[0];
                      return fnames = arguments[1];
                    };
                  })(_this),
                  lineno: 71
                }));
                __iced_deferrals._fulfill();
              })(function() {
                return __iced_k(typeof fnames !== "undefined" && fnames !== null ? _this._dir_contents = (function() {
                  var _i, _len, _results;
                  _results = [];
                  for (_i = 0, _len = fnames.length; _i < _len; _i++) {
                    f = fnames[_i];
                    if (f !== '.') {
                      _results.push(f);
                    }
                  }
                  return _results;
                })() : void 0);
              });
            } else {
              return __iced_k();
            }
          })(function() {
            lock.release();
            return cb(_this.err, _this._dir_contents);
          });
        };
      })(this));
    };

    FileInfo.prototype.readlink = function(cb) {
      var lock, ___iced_passed_deferral, __iced_deferrals, __iced_k;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      this.check_init();
      (function(_this) {
        return (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "/Users/chris/git/keybase/dir-summarize/src/file_info_cache.iced",
            funcname: "FileInfo.readlink"
          });
          _this._locks.acquire('readlink', __iced_deferrals.defer({
            assign_fn: (function() {
              return function() {
                return lock = arguments[0];
              };
            })(),
            lineno: 80
          }), true);
          __iced_deferrals._fulfill();
        });
      })(this)((function(_this) {
        return function() {
          (function(__iced_k) {
            if ((!_this.err) && (_this._link == null)) {
              (function(__iced_k) {
                __iced_deferrals = new iced.Deferrals(__iced_k, {
                  parent: ___iced_passed_deferral,
                  filename: "/Users/chris/git/keybase/dir-summarize/src/file_info_cache.iced",
                  funcname: "FileInfo.readlink"
                });
                fs.readlink(_this.full_path, __iced_deferrals.defer({
                  assign_fn: (function(__slot_1, __slot_2) {
                    return function() {
                      __slot_1.err = arguments[0];
                      return __slot_2._link = arguments[1];
                    };
                  })(_this, _this),
                  lineno: 82
                }));
                __iced_deferrals._fulfill();
              })(__iced_k);
            } else {
              return __iced_k();
            }
          })(function() {
            lock.release();
            return cb(_this.err, _this._link);
          });
        };
      })(this));
    };

    FileInfo.prototype.is_binary = function(cb) {
      var b, bytes_read, fd, i, len, lock, ___iced_passed_deferral, __iced_deferrals, __iced_k;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      this.check_init();
      (function(_this) {
        return (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "/Users/chris/git/keybase/dir-summarize/src/file_info_cache.iced",
            funcname: "FileInfo.is_binary"
          });
          _this._locks.acquire('is_binary', __iced_deferrals.defer({
            assign_fn: (function() {
              return function() {
                return lock = arguments[0];
              };
            })(),
            lineno: 90
          }), true);
          __iced_deferrals._fulfill();
        });
      })(this)((function(_this) {
        return function() {
          (function(__iced_k) {
            if ((!_this.err) && (_this._is_binary == null)) {
              (function(__iced_k) {
                if (!_this.lstat.isFile()) {
                  return __iced_k(_this._is_binary = false);
                } else {
                  (function(__iced_k) {
                    __iced_deferrals = new iced.Deferrals(__iced_k, {
                      parent: ___iced_passed_deferral,
                      filename: "/Users/chris/git/keybase/dir-summarize/src/file_info_cache.iced",
                      funcname: "FileInfo.is_binary"
                    });
                    fs.open(_this.full_path, 'r', __iced_deferrals.defer({
                      assign_fn: (function(__slot_1) {
                        return function() {
                          __slot_1.err = arguments[0];
                          return fd = arguments[1];
                        };
                      })(_this),
                      lineno: 95
                    }));
                    __iced_deferrals._fulfill();
                  })(function() {
                    (function(__iced_k) {
                      if (!_this.err) {
                        len = Math.min(_this.stat.size, _this._BINARY_BYTE_STUDY);
                        (function(__iced_k) {
                          if (!len) {
                            return __iced_k(_this._is_binary = true);
                          } else {
                            b = new Buffer(len);
                            (function(__iced_k) {
                              __iced_deferrals = new iced.Deferrals(__iced_k, {
                                parent: ___iced_passed_deferral,
                                filename: "/Users/chris/git/keybase/dir-summarize/src/file_info_cache.iced",
                                funcname: "FileInfo.is_binary"
                              });
                              fs.read(fd, b, 0, len, 0, __iced_deferrals.defer({
                                assign_fn: (function(__slot_1) {
                                  return function() {
                                    __slot_1.err = arguments[0];
                                    return bytes_read = arguments[1];
                                  };
                                })(_this),
                                lineno: 102
                              }));
                              __iced_deferrals._fulfill();
                            })(function() {
                              var _i, _ref;
                              if (bytes_read !== len) {
                                console.log("#Requested " + len + " bytes of " + _this.full_path + ", but got " + bytes_read);
                              }
                              _this._is_binary = false;
                              for (i = _i = 0, _ref = b.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
                                if (b.readUInt8(i) === 0) {
                                  _this._is_binary = true;
                                  break;
                                }
                              }
                              return __iced_k();
                            });
                          }
                        })(function() {
                          (function(__iced_k) {
                            __iced_deferrals = new iced.Deferrals(__iced_k, {
                              parent: ___iced_passed_deferral,
                              filename: "/Users/chris/git/keybase/dir-summarize/src/file_info_cache.iced",
                              funcname: "FileInfo.is_binary"
                            });
                            fs.close(fd, __iced_deferrals.defer({
                              assign_fn: (function(__slot_1) {
                                return function() {
                                  return __slot_1.err = arguments[0];
                                };
                              })(_this),
                              lineno: 110
                            }));
                            __iced_deferrals._fulfill();
                          })(__iced_k);
                        });
                      } else {
                        return __iced_k();
                      }
                    })(__iced_k);
                  });
                }
              })(__iced_k);
            } else {
              return __iced_k();
            }
          })(function() {
            lock.release();
            return cb(_this.err, _this._is_binary);
          });
        };
      })(this));
    };

    FileInfo.prototype.is_user_executable_file = function() {
      this.check_init();
      return this.lstat.isFile() && !!(parseInt(100, 8) & this.lstat.mode);
    };

    return FileInfo;

  })();

  InfoCollection = (function() {
    function InfoCollection() {
      this._locks = new LockTable();
      this._cache = {};
    }

    InfoCollection.prototype.get = function(f, cb) {
      var lock, ___iced_passed_deferral, __iced_deferrals, __iced_k;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      f = path.resolve(f);
      (function(_this) {
        return (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "/Users/chris/git/keybase/dir-summarize/src/file_info_cache.iced",
            funcname: "InfoCollection.get"
          });
          _this._locks.acquire(f, __iced_deferrals.defer({
            assign_fn: (function() {
              return function() {
                return lock = arguments[0];
              };
            })(),
            lineno: 137
          }), true);
          __iced_deferrals._fulfill();
        });
      })(this)((function(_this) {
        return function() {
          (function(__iced_k) {
            if (_this._cache[f] == null) {
              _this._cache[f] = new FileInfo(f);
              (function(__iced_k) {
                __iced_deferrals = new iced.Deferrals(__iced_k, {
                  parent: ___iced_passed_deferral,
                  filename: "/Users/chris/git/keybase/dir-summarize/src/file_info_cache.iced",
                  funcname: "InfoCollection.get"
                });
                _this._cache[f].init(__iced_deferrals.defer({
                  lineno: 140
                }));
                __iced_deferrals._fulfill();
              })(__iced_k);
            } else {
              return __iced_k();
            }
          })(function() {
            lock.release();
            return cb(_this._cache[f].err, _this._cache[f]);
          });
        };
      })(this));
    };

    return InfoCollection;

  })();

  ic = new InfoCollection();

  module.exports = function(f, cb) {
    return ic.get(f, cb);
  };

}).call(this);
