// Generated by IcedCoffeeScript 1.7.1-b
(function() {
  var ArgumentParser, Main, PackageJson;

  ArgumentParser = require('argparse').ArgumentParser;

  PackageJson = require('./package').PackageJson;

  Main = (function() {
    function Main() {
      this.pkjson = new PackageJson();
      this.init_parser();
    }

    Main.prototype.init_parser = function() {
      return this.ap = new ArgumentParser({
        addHelp: true,
        version: this.pkjson.version(),
        description: 'keybase.io directory summarizer',
        prog: this.pkjson.bin()
      });
    };

    Main.prototype.run = function() {
      return console.log("It's really running.");
    };

    return Main;

  })();

  exports.run = function() {
    return (new Main()).run();
  };

}).call(this);
