// Generated by IcedCoffeeScript 1.7.1-b

/*

  A serializer/deserialized for Markdown from summarizer objects
 */

(function() {
  exports.to_md = function(o) {
    var f, file_list, ignore_list, res;
    ignore_list = o.exclude.join('\n');
    file_list = ((function() {
      var _i, _len, _ref, _results;
      _ref = o.found;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        f = _ref[_i];
        _results.push(JSON.stringify(f));
      }
      return _results;
    })()).join('\n');
    res = "#### Verify\n\n```\n" + file_list + "\n```\n\n#### Ignore\n\n```\n" + ignore_list + "\n```";
    return res;
  };

  exports.from_md = function(str) {
    var match, rxx;
    rxx = /^\s*\#\#\#\#\sVerify\s*```([^`]*)```\s*\#\#\#\#\sIgnore\s*```([^`]*)```\s*$/;
    match = rxx.exec(str);
    console.log(0);
    console.log(match[0]);
    console.log(1);
    console.log(match[1]);
    console.log(2);
    return console.log(match[2]);
  };

}).call(this);
