// Generated by IcedCoffeeScript 1.7.1-b
(function() {
  var SummarizedItem, Summarizer, crypto, fs, iced, item_types, make_esc, path, tablify, __iced_k, __iced_k_noop;

  iced = require('iced-coffee-script/lib/coffee-script/iced').runtime;
  __iced_k = __iced_k_noop = function() {};

  crypto = require('crypto');

  tablify = require('tablify');

  path = require('path');

  fs = require('fs');

  make_esc = require('iced-error').make_esc;

  item_types = {
    FILE: 0,
    DIR: 1,
    SYMLINK: 2
  };

  SummarizedItem = (function() {
    function SummarizedItem(_arg) {
      var fname, parent_path, summarizer;
      parent_path = _arg.parent_path, fname = _arg.fname, summarizer = _arg.summarizer;
      this.parent_path = parent_path;
      this.fname = fname;
      this.summarizer = summarizer;
      this.item_type = null;
      this.realpath = null;
      this.link = null;
      this.contents = null;
      this.hash = null;
      this.fstats = null;
      this.flstats = null;
    }

    SummarizedItem.prototype.load_traverse = function(cb) {
      var esc, f, fnames, p, si, ___iced_passed_deferral, __iced_deferrals, __iced_k;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      esc = make_esc(cb, "SummarizedItem::load");
      p = path.join(this.summarizer.root_dir(), this.parent_path, this.fname);
      (function(_this) {
        return (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "/Users/chris/git/keybase/dir-summarize/src/summarizer.iced",
            funcname: "SummarizedItem.load_traverse"
          });
          fs.realpath(p, esc(__iced_deferrals.defer({
            assign_fn: (function(__slot_1) {
              return function() {
                return __slot_1.realpath = arguments[0];
              };
            })(_this),
            lineno: 34
          })));
          __iced_deferrals._fulfill();
        });
      })(this)((function(_this) {
        return function() {
          (function(__iced_k) {
            __iced_deferrals = new iced.Deferrals(__iced_k, {
              parent: ___iced_passed_deferral,
              filename: "/Users/chris/git/keybase/dir-summarize/src/summarizer.iced",
              funcname: "SummarizedItem.load_traverse"
            });
            fs.lstat(p, esc(__iced_deferrals.defer({
              assign_fn: (function(__slot_1) {
                return function() {
                  return __slot_1.flstats = arguments[0];
                };
              })(_this),
              lineno: 35
            })));
            __iced_deferrals._fulfill();
          })(function() {
            (function(__iced_k) {
              var _ref;
              if ((_ref = _this.flstats) != null ? _ref.isSymbolicLink() : void 0) {
                _this.item_type = item_types.SYMLINK;
                (function(__iced_k) {
                  __iced_deferrals = new iced.Deferrals(__iced_k, {
                    parent: ___iced_passed_deferral,
                    filename: "/Users/chris/git/keybase/dir-summarize/src/summarizer.iced",
                    funcname: "SummarizedItem.load_traverse"
                  });
                  fs.stat(p, esc(__iced_deferrals.defer({
                    assign_fn: (function(__slot_1) {
                      return function() {
                        return __slot_1.fstats = arguments[0];
                      };
                    })(_this),
                    lineno: 38
                  })));
                  __iced_deferrals._fulfill();
                })(function() {
                  (function(__iced_k) {
                    __iced_deferrals = new iced.Deferrals(__iced_k, {
                      parent: ___iced_passed_deferral,
                      filename: "/Users/chris/git/keybase/dir-summarize/src/summarizer.iced",
                      funcname: "SummarizedItem.load_traverse"
                    });
                    fs.readlink(p, esc(__iced_deferrals.defer({
                      assign_fn: (function(__slot_1) {
                        return function() {
                          return __slot_1.link = arguments[0];
                        };
                      })(_this),
                      lineno: 39
                    })));
                    __iced_deferrals._fulfill();
                  })(__iced_k);
                });
              } else {
                (function(__iced_k) {
                  if (_this.flstats.isFile()) {
                    _this.fstats = _this.flstats;
                    _this.item_type = item_types.FILE;
                    (function(__iced_k) {
                      __iced_deferrals = new iced.Deferrals(__iced_k, {
                        parent: ___iced_passed_deferral,
                        filename: "/Users/chris/git/keybase/dir-summarize/src/summarizer.iced",
                        funcname: "SummarizedItem.load_traverse"
                      });
                      _this.hash_contents(esc(__iced_deferrals.defer({
                        assign_fn: (function(__slot_1) {
                          return function() {
                            return __slot_1.hash = arguments[0];
                          };
                        })(_this),
                        lineno: 43
                      })));
                      __iced_deferrals._fulfill();
                    })(__iced_k);
                  } else {
                    _this.contents = [];
                    _this.fstats = _this.flstats;
                    _this.item_type = item_types.DIR;
                    (function(__iced_k) {
                      __iced_deferrals = new iced.Deferrals(__iced_k, {
                        parent: ___iced_passed_deferral,
                        filename: "/Users/chris/git/keybase/dir-summarize/src/summarizer.iced",
                        funcname: "SummarizedItem.load_traverse"
                      });
                      fs.readdir(_this.realpath, esc(__iced_deferrals.defer({
                        assign_fn: (function() {
                          return function() {
                            return fnames = arguments[0];
                          };
                        })(),
                        lineno: 48
                      })));
                      __iced_deferrals._fulfill();
                    })(function() {
                      (function(__iced_k) {
                        var _i, _len, _ref1, _results, _while;
                        _ref1 = fnames;
                        _len = _ref1.length;
                        _i = 0;
                        _results = [];
                        _while = function(__iced_k) {
                          var _break, _continue, _next;
                          _break = function() {
                            return __iced_k(_results);
                          };
                          _continue = function() {
                            return iced.trampoline(function() {
                              ++_i;
                              return _while(__iced_k);
                            });
                          };
                          _next = function(__iced_next_arg) {
                            _results.push(__iced_next_arg);
                            return _continue();
                          };
                          if (!(_i < _len)) {
                            return _break();
                          } else {
                            f = _ref1[_i];
                            si = _this.subitem(f);
                            (function(__iced_k) {
                              __iced_deferrals = new iced.Deferrals(__iced_k, {
                                parent: ___iced_passed_deferral,
                                filename: "/Users/chris/git/keybase/dir-summarize/src/summarizer.iced",
                                funcname: "SummarizedItem.load_traverse"
                              });
                              si.load_traverse(esc(__iced_deferrals.defer({
                                lineno: 51
                              })));
                              __iced_deferrals._fulfill();
                            })(function() {
                              return _next(_this.contents.push(si));
                            });
                          }
                        };
                        _while(__iced_k);
                      })(__iced_k);
                    });
                  }
                })(__iced_k);
              }
            })(function() {
              return cb();
            });
          });
        };
      })(this));
    };

    SummarizedItem.prototype.subitem = function(f) {
      return new SummarizedItem({
        fname: f,
        parent_path: path.join(this.parent_path, this.fname),
        summarizer: this.summarizer
      });
    };

    SummarizedItem.prototype.to_str = function(depth) {
      var c, i, indent, label;
      depth = depth || 0;
      indent = ((function() {
        var _i, _results;
        _results = [];
        for (i = _i = 0; 0 <= depth ? _i < depth : _i > depth; i = 0 <= depth ? ++_i : --_i) {
          _results.push("   ");
        }
        return _results;
      })()).join("");
      label = indent + path.normalize(path.join(this.parent_path, this.fname));
      switch (this.item_type) {
        case item_types.FILE:
          return "\n" + label + "      " + this.hash;
        case item_types.SYMLINK:
          return "\n" + label + "   -> " + this.link;
        case item_types.DIR:
          Summarizer.sort_items(this.contents);
          return ("\n" + label + "/") + ((function() {
            var _i, _len, _ref, _results;
            _ref = this.contents;
            _results = [];
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              c = _ref[_i];
              _results.push(c.to_str(depth + 1));
            }
            return _results;
          }).call(this)).join("");
      }
    };

    SummarizedItem.prototype.hash_contents = function(cb) {
      var fd, hash;
      fd = fs.createReadStream(this.realpath);
      hash = crypto.createHash('sha256');
      hash.setEncoding('hex');
      fd.on('end', function() {
        hash.end();
        return cb(null, hash.read());
      });
      fd.on('error', function(e) {
        return cb(e);
      });
      return fd.pipe(hash);
    };

    return SummarizedItem;

  })();

  Summarizer = (function() {
    function Summarizer(opts) {
      var _base, _base1;
      this.root_item = null;
      this.opts = opts || {};
      (_base = this.opts).exclude || (_base.exclude = []);
      (_base1 = this.opts).root_dir || (_base1.root_dir = '.');
    }

    Summarizer.prototype.set_root_item = function(ri) {
      return this.root_item = ri;
    };

    Summarizer.prototype.root_dir = function() {
      return this.opts.root_dir;
    };

    Summarizer.from_str = function(str) {

      /*
      takes a summary string (generated by to_str) and builds a Summarizer
       */
    };

    Summarizer.from_dir = function(dir, opts, cb) {
      var err, root_item, summ, ___iced_passed_deferral, __iced_deferrals, __iced_k;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);

      /*
      takes the path to a directory and returns a Summarize instance
       */
      opts = opts || {};
      opts.root_dir || (opts.root_dir = dir);
      summ = new Summarizer(opts);
      err = null;
      root_item = new SummarizedItem({
        fname: '.',
        parent_path: '',
        summarizer: summ
      });
      (function(_this) {
        return (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "/Users/chris/git/keybase/dir-summarize/src/summarizer.iced",
            funcname: "Summarizer.from_dir"
          });
          root_item.load_traverse(__iced_deferrals.defer({
            assign_fn: (function() {
              return function() {
                return err = arguments[0];
              };
            })(),
            lineno: 133
          }));
          __iced_deferrals._fulfill();
        });
      })(this)((function(_this) {
        return function() {
          if (err == null) {
            summ.set_root_item(root_item);
          } else {
            console.log(err);
          }
          return cb(err, summ);
        };
      })(this));
    };

    Summarizer.diff = function(s1, s2) {

      /*
      returns a diff of two Summarized directories
       */
    };

    Summarizer.sort_items = function(items) {
      items.sort(function(a, b) {
        return a.fname.localeCompare(b.fname);
      });
      return items;
    };

    Summarizer.prototype.to_str = function() {

      /*
      returns a pretty string, which is also
      parsable by from_str
       */
      return this.root_item.to_str(0);
    };

    return Summarizer;

  })();

  exports.Summarizer = Summarizer;

}).call(this);
