// Generated by IcedCoffeeScript 1.7.1-b
(function() {
  module.exports = {
    escape: function(s) {

      /*
      we don't want to use either escape (deprecated) or encodeURIComponent (too ugly) and overescapes
       */
      var c, i, res, _i, _len;
      res = '';
      for (i = _i = 0, _len = s.length; _i < _len; i = ++_i) {
        c = s[i];
        if (c.match(/^[a-z0-9\/\._\-\~\#]$/i)) {
          res += c;
        } else {
          res += encodeURIComponent(c).replace(/%20/g, '+');
        }
      }
      return res;
    },
    unescape: function(s) {
      return decodeURIComponent(s.replace(/\+/g, '%20'));
    },
    is_user_executable: function(mode) {
      return !!(parseInt(100, 8) & mode);
    }
  };

}).call(this);
